// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPesvHJ0--fX_k_N5LdC_sDe56cNqMy0',
    appId: '1:446399565442:web:c71629a58d2dd7f73bee9b',
    messagingSenderId: '446399565442',
    projectId: 'khadamat-d9a5a',
    authDomain: 'khadamat-d9a5a.firebaseapp.com',
    storageBucket: 'khadamat-d9a5a.firebasestorage.app',
    measurementId: 'G-KJT1EC2L5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJar3qUks5FGEwdf3Mk_Y-8RsJLsKCIuQ',
    appId: '1:446399565442:android:0e6ae259b1143dad3bee9b',
    messagingSenderId: '446399565442',
    projectId: 'khadamat-d9a5a',
    storageBucket: 'khadamat-d9a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisxAYSImLWO3mHNGu1iPDJjAu_DG__TE',
    appId: '1:446399565442:ios:d43c3671d2c9feaa3bee9b',
    messagingSenderId: '446399565442',
    projectId: 'khadamat-d9a5a',
    storageBucket: 'khadamat-d9a5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterProduct1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCisxAYSImLWO3mHNGu1iPDJjAu_DG__TE',
    appId: '1:446399565442:ios:d43c3671d2c9feaa3bee9b',
    messagingSenderId: '446399565442',
    projectId: 'khadamat-d9a5a',
    storageBucket: 'khadamat-d9a5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterProduct1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkPesvHJ0--fX_k_N5LdC_sDe56cNqMy0',
    appId: '1:446399565442:web:90630ac1995841233bee9b',
    messagingSenderId: '446399565442',
    projectId: 'khadamat-d9a5a',
    authDomain: 'khadamat-d9a5a.firebaseapp.com',
    storageBucket: 'khadamat-d9a5a.firebasestorage.app',
    measurementId: 'G-K309Q2M61Z',
  );
}
